[package]
name = "ensourcel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
from-pest = "0.3.1"
pest = "2.4.1"
pest-ast = "0.3.3"
pest_derive = "2.4.1"
